### ISSUE TITLE
What is HTML? & Basic Syntax

### ISSUE THREAD

**Issue by sarvaratchagan** [sarvaratchagan/knowledge#7]

**Comment by OmarHattab** [comment]
-HTML is stand for ( HYPER Text Markup Language) and its a a Markup language for creating Web Pages.
Basic Syntax : 
<HTML>
   <HEAD>
        <!-- Meta Data about web page  --!>  
  </HEAD>
    <Body>
     <!-- content of the page --!>
    <Body>
</HTML>
