### ISSUE TITLE
Give me the purpose of <head> tag  in Html. What all are the elements can be found inside this element

### ISSUE THREAD

**Issue by sarvaratchagan** [sarvaratchagan/knowledge#8]

**Comment by OmarHattab** [comment]
`<Header>`
Purpose : to represent a container for introductory content or a set of navigational links.
elements : (`<h1>` ..`<h6>`) , logo or icones  , `<p>` authorship information `</p>`

`<HEAD> `
Purpose : its a container of all other  header Elements which are the meta data of current web page.
Elements are : `<title> , <Style> , <link> , <script>, <meta>`
